### ISSUE TITLE
Reloading is broken in 9.26

### ISSUE THREAD

**Issue by rnhmjoj** [regnarg/urxvt-config-reload#20] opened 2021-06-03 14:58 UTC
The plugin stopped working in rxvt-unicode 9.26. 
After a lengthy bisection of the project history I found out this is the change that broke it:

```diff
commit 7e804cd0f4edd5f2f60f39d8baf4f872b6d63756
Author: Marc Lehmann <schmorp@schmorp.de>
Date:   Tue Jun 30 07:31:24 2020 +0000

    do not call perl_destruct

diff --git a/Changes b/Changes
index c77a58f1..c0b53f2e 100644
--- a/Changes
+++ b/Changes
@@ -45,6 +45,8 @@ TODO: confirm-paste should be the default
 TODO: xterm-osc does not autoload background
 TODO: think about daemon delaying urxvt client exit.
 TODO: libev update
+	- do not destruct perl on exit anymore: this might fail for a variety of
+          reasons, and takes unneccessary time.
 	- the old bg image resources are now provided by the background
 	  extension, and perl is thus required for bg image support. No
 	  configuration change is needed: urxvt autoloads the background
diff --git a/src/rxvtperl.h b/src/rxvtperl.h
index 0e50e8fb..d559009f 100644
--- a/src/rxvtperl.h
+++ b/src/rxvtperl.h
@@ -51,7 +51,9 @@ struct rxvt_perl_interp
 {
   char **perl_environ;
 
+  #if 0 // see rxvtperl.xs
   ~rxvt_perl_interp ();
+  #endif
 
   void init ();
   void init (rxvt_term *term);
diff --git a/src/rxvtperl.xs b/src/rxvtperl.xs
index abfcfd47..c22a1d33 100644
--- a/src/rxvtperl.xs
+++ b/src/rxvtperl.xs
@@ -372,6 +372,9 @@ struct rxvt_perl_interp rxvt_perl;
 
 static PerlInterpreter *perl;
 
+#if 0 /* we are not a library anymore, so doing this is just not worth it */
+/*THINK/TODO: this has the side effect of, of course, not calling destructors. */
+/* but therse are not guaranteed anyway... */
 rxvt_perl_interp::~rxvt_perl_interp ()
 {
   if (perl)
@@ -381,6 +384,7 @@ rxvt_perl_interp::~rxvt_perl_interp ()
       PERL_SYS_TERM ();
     }
 }
+#endif
 
 void
 rxvt_perl_interp::init ()

```
Not sure why and what to do now.

**Comment by qualiaa** [comment] 2021-06-03 15:26
Thanks for flagging this - I've had a quick look into it and it seems that the `config-print` call isn't yielding a string (though running it directly has the expected behaviour).

I'll look into it tonight.

**Comment by qualiaa** [comment] 2021-06-03 19:11
@rnhmjoj I've just pushed a fix, maybe you could verify it works on your end? I'll also add it to my fork, which has a few minor improvements.

**Comment by exg** [comment] 2021-06-04 19:19
The issue is due to perl STDOUT no longer being flushed as a result of the perl interpreter not being destroyed. Note that the behaviour when an extension calls `exit` is not specified; extensions are not supposed to terminate urxvt. To fix the extension it would be enough to invoke `STDOUT->flush()` before `exit`, but replacing the `config-print` hack with `xrdb` is a better change.

**Comment by qualiaa** [comment] 2021-06-05 19:21
Ah, that explains it! Thanks for the info. If you know, I wonder why running it from within another terminal produces the output while within Perl backticks does not? My intuition is that the `stdout` is the tty and thus nothing is lost, but why is Perl's behaviour different?

**Comment by exg** [comment] 2021-06-05 19:44
> If you know, I wonder why running it from within another terminal produces the output while within Perl backticks does not?

`STDOUT` is line-buffered when connected to a tty, fully-buffered when connected to a pipe (backticks).

**Closed** 2021-06-28 13:34 UTC
